AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Nephos Cloud Monitoring Infrastructure

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  VultrApiKey:
    Type: String
    NoEcho: true
    Description: Vultr API Key for instance monitoring

  SnowflakeAccount:
    Type: String
    Description: Snowflake account identifier

  SnowflakeUser:
    Type: String
    Description: Snowflake username

  SnowflakePassword:
    Type: String
    NoEcho: true
    Description: Snowflake password

  SnowflakeWarehouse:
    Type: String
    Default: SNOWFLAKE_LEARNING_WH
    Description: Snowflake warehouse name

  SnowflakeDatabase:
    Type: String
    Default: NEPHOS
    Description: Snowflake database name

  SnowflakeSchema:
    Type: String
    Default: PUBLIC
    Description: Snowflake schema name

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        DYNAMODB_TABLE_METRICS: !Ref MetricsTable
        DYNAMODB_TABLE_ALERTS: !Ref AlertsTable
        DYNAMODB_TABLE_INSTANCES: !Ref InstancesTable
        REGION: !Ref AWS::Region

Resources:
  # ========================================
  # DynamoDB Tables
  # ========================================

  MetricsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub CloudPulseMetrics-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: instanceId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: InstanceIdIndex
          KeySchema:
            - AttributeName: instanceId
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: Nephos

  AlertsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub CloudPulseAlerts-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: instanceId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: InstanceIdIndex
          KeySchema:
            - AttributeName: instanceId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: Nephos

  InstancesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub CloudPulseInstances-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: Nephos

  # ========================================
  # SNS Topics
  # ========================================

  AlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub nephos-alerts-${Environment}
      DisplayName: Nephos Critical Alerts
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: Nephos

  # ========================================
  # Lambda Functions
  # ========================================

  # Sentinel Function - Health Monitoring
  SentinelFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub nephos-sentinel-${Environment}
      CodeUri: functions/sentinel/
      Handler: index.handler
      Description: Health monitoring and active checks for Vultr instances
      Environment:
        Variables:
          VULTR_API_KEY: !Ref VultrApiKey
          SNS_TOPIC_ARN: !Ref AlertsTopic
          HEALTH_CHECK_TIMEOUT: 5000
      Events:
        ScheduledCheck:
          Type: Schedule
          Properties:
            Schedule: rate(2 minutes)
            Description: Run health checks every 2 minutes
            Enabled: true
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MetricsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AlertsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref InstancesTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt AlertsTopic.TopicName
      Tags:
        Environment: !Ref Environment
        Application: Nephos

  # Vultr Metrics Ingestion Function
  VultrIngestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub nephos-vultr-ingestion-${Environment}
      CodeUri: functions/ingest/vultr-metrics/
      Handler: index.handler
      Description: Receives and ingests metrics from Vultr instances
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /ingest
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MetricsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AlertsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref InstancesTable
      Tags:
        Environment: !Ref Environment
        Application: Nephos

  # ETL Function - DynamoDB to Snowflake
  ETLFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub nephos-etl-${Environment}
      CodeUri: functions/etl/dynamodb-to-snowflake/
      Handler: index.handler
      Description: Syncs DynamoDB data to Snowflake for AI analysis
      Timeout: 300
      MemorySize: 1024
      Environment:
        Variables:
          SNOWFLAKE_ACCOUNT: !Ref SnowflakeAccount
          SNOWFLAKE_USERNAME: !Ref SnowflakeUser
          SNOWFLAKE_PASSWORD: !Ref SnowflakePassword
          SNOWFLAKE_WAREHOUSE: !Ref SnowflakeWarehouse
          SNOWFLAKE_DATABASE: !Ref SnowflakeDatabase
          SNOWFLAKE_SCHEMA: !Ref SnowflakeSchema
      Events:
        MetricsStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt MetricsTable.StreamArn
            StartingPosition: LATEST
            BatchSize: 100
            MaximumBatchingWindowInSeconds: 10
        AlertsStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt AlertsTable.StreamArn
            StartingPosition: LATEST
            BatchSize: 100
            MaximumBatchingWindowInSeconds: 10
        InstancesStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt InstancesTable.StreamArn
            StartingPosition: LATEST
            BatchSize: 100
            MaximumBatchingWindowInSeconds: 10
        ScheduledSync:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
            Description: Hourly batch sync to Snowflake
            Enabled: true
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MetricsTable
        - DynamoDBReadPolicy:
            TableName: !Ref AlertsTable
        - DynamoDBReadPolicy:
            TableName: !Ref InstancesTable
        - DynamoDBStreamReadPolicy:
            TableName: !Ref MetricsTable
            StreamName: !Select [3, !Split ["/", !GetAtt MetricsTable.StreamArn]]
        - DynamoDBStreamReadPolicy:
            TableName: !Ref AlertsTable
            StreamName: !Select [3, !Split ["/", !GetAtt AlertsTable.StreamArn]]
        - DynamoDBStreamReadPolicy:
            TableName: !Ref InstancesTable
            StreamName: !Select [3, !Split ["/", !GetAtt InstancesTable.StreamArn]]
      Tags:
        Environment: !Ref Environment
        Application: Nephos

  # API Functions
  InsightsApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub nephos-insights-api-${Environment}
      CodeUri: functions/api/insights/
      Handler: index.handler
      Description: AI Insights API powered by Snowflake Cortex
      Environment:
        Variables:
          SNOWFLAKE_ACCOUNT: !Ref SnowflakeAccount
          SNOWFLAKE_USERNAME: !Ref SnowflakeUser
          SNOWFLAKE_PASSWORD: !Ref SnowflakePassword
          SNOWFLAKE_WAREHOUSE: !Ref SnowflakeWarehouse
          SNOWFLAKE_DATABASE: !Ref SnowflakeDatabase
          SNOWFLAKE_SCHEMA: !Ref SnowflakeSchema
      Events:
        GetInsights:
          Type: HttpApi
          Properties:
            Path: /insights
            Method: GET
        GetSummary:
          Type: HttpApi
          Properties:
            Path: /insights/summary
            Method: GET
        GetPatterns:
          Type: HttpApi
          Properties:
            Path: /insights/patterns
            Method: GET
        GetAnomalies:
          Type: HttpApi
          Properties:
            Path: /insights/anomalies
            Method: GET
        GetPredictions:
          Type: HttpApi
          Properties:
            Path: /insights/predictions
            Method: GET
      Tags:
        Environment: !Ref Environment
        Application: Nephos

  AnalyticsApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub nephos-analytics-api-${Environment}
      CodeUri: functions/api/analytics/
      Handler: index.handler
      Description: Analytics and dashboard API
      Events:
        GetDashboard:
          Type: HttpApi
          Properties:
            Path: /analytics/dashboard
            Method: GET
        GetAnalytics:
          Type: HttpApi
          Properties:
            Path: /analytics
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MetricsTable
        - DynamoDBReadPolicy:
            TableName: !Ref AlertsTable
        - DynamoDBReadPolicy:
            TableName: !Ref InstancesTable
      Tags:
        Environment: !Ref Environment
        Application: Nephos

  AlertsApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub nephos-alerts-api-${Environment}
      CodeUri: functions/api/alerts/
      Handler: index.handler
      Description: Alerts management API
      Events:
        GetAlerts:
          Type: HttpApi
          Properties:
            Path: /alerts
            Method: GET
        GetAlert:
          Type: HttpApi
          Properties:
            Path: /alerts/{id}
            Method: GET
        UpdateAlert:
          Type: HttpApi
          Properties:
            Path: /alerts/{id}
            Method: PUT
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AlertsTable
      Tags:
        Environment: !Ref Environment
        Application: Nephos

  # ========================================
  # WebSocket API for Real-time Updates
  # ========================================

  WebSocketConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub NephosWebSocketConnections-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: Nephos

  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub nephos-websocket-${Environment}
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action

  WebSocketConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub nephos-ws-connect-${Environment}
      CodeUri: functions/websocket/connect/
      Handler: index.handler
      Description: WebSocket connection handler
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref WebSocketConnectionsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref WebSocketConnectionsTable
      Tags:
        Environment: !Ref Environment
        Application: Nephos

  WebSocketDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub nephos-ws-disconnect-${Environment}
      CodeUri: functions/websocket/disconnect/
      Handler: index.handler
      Description: WebSocket disconnect handler
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref WebSocketConnectionsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref WebSocketConnectionsTable
      Tags:
        Environment: !Ref Environment
        Application: Nephos

  WebSocketBroadcastFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub nephos-ws-broadcast-${Environment}
      CodeUri: functions/websocket/broadcast/
      Handler: index.handler
      Description: Broadcasts real-time updates to all connected clients
      Timeout: 60
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref WebSocketConnectionsTable
          WEBSOCKET_ENDPOINT: !Sub https://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${WebSocketStage}
      Events:
        MetricsStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt MetricsTable.StreamArn
            StartingPosition: LATEST
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 1
        AlertsStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt AlertsTable.StreamArn
            StartingPosition: LATEST
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 1
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref WebSocketConnectionsTable
        - DynamoDBStreamReadPolicy:
            TableName: !Ref MetricsTable
            StreamName: !Select [3, !Split ["/", !GetAtt MetricsTable.StreamArn]]
        - DynamoDBStreamReadPolicy:
            TableName: !Ref AlertsTable
            StreamName: !Select [3, !Split ["/", !GetAtt AlertsTable.StreamArn]]
        - Statement:
            - Effect: Allow
              Action:
                - execute-api:ManageConnections
              Resource: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*
      Tags:
        Environment: !Ref Environment
        Application: Nephos

  WebSocketConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketConnectFunction.Arn}/invocations

  WebSocketDisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketDisconnectFunction.Arn}/invocations

  WebSocketConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $connect
      Target: !Sub integrations/${WebSocketConnectIntegration}

  WebSocketDisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $disconnect
      Target: !Sub integrations/${WebSocketDisconnectIntegration}

  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref WebSocketApi
      StageName: !Ref Environment
      Description: !Sub ${Environment} stage for WebSocket API
      AutoDeploy: true

  WebSocketConnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WebSocketConnectFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*

  WebSocketDisconnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WebSocketDisconnectFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*

  # ========================================
  # CloudWatch Log Groups
  # ========================================

  SentinelLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${SentinelFunction}
      RetentionInDays: 7

  VultrIngestionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${VultrIngestionFunction}
      RetentionInDays: 7

  ETLLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ETLFunction}
      RetentionInDays: 14

Outputs:
  # API Endpoints
  VultrIngestionEndpoint:
    Description: Vultr Metrics Ingestion Endpoint
    Value: !Sub https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/ingest
    Export:
      Name: !Sub ${Environment}-VultrIngestionEndpoint

  InsightsApiEndpoint:
    Description: AI Insights API Endpoint
    Value: !Sub https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/insights
    Export:
      Name: !Sub ${Environment}-InsightsApiEndpoint

  AnalyticsApiEndpoint:
    Description: Analytics Dashboard API Endpoint
    Value: !Sub https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/analytics
    Export:
      Name: !Sub ${Environment}-AnalyticsApiEndpoint

  WebSocketEndpoint:
    Description: WebSocket API Endpoint for Real-time Updates
    Value: !Sub wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${WebSocketStage}
    Export:
      Name: !Sub ${Environment}-WebSocketEndpoint

  # DynamoDB Tables
  MetricsTableName:
    Description: Metrics DynamoDB Table Name
    Value: !Ref MetricsTable
    Export:
      Name: !Sub ${Environment}-MetricsTableName

  AlertsTableName:
    Description: Alerts DynamoDB Table Name
    Value: !Ref AlertsTable
    Export:
      Name: !Sub ${Environment}-AlertsTableName

  InstancesTableName:
    Description: Instances DynamoDB Table Name
    Value: !Ref InstancesTable
    Export:
      Name: !Sub ${Environment}-InstancesTableName

  # SNS Topic
  AlertsTopicArn:
    Description: SNS Topic ARN for Critical Alerts
    Value: !Ref AlertsTopic
    Export:
      Name: !Sub ${Environment}-AlertsTopicArn

  # Lambda Functions
  SentinelFunctionArn:
    Description: Sentinel Function ARN
    Value: !GetAtt SentinelFunction.Arn
    Export:
      Name: !Sub ${Environment}-SentinelFunctionArn
