import { NextResponse } from 'next/server';

// Mock data for local development
// Replace with actual AWS Lambda calls in production

export async function GET() {
  // Generate mock dashboard data
  const mockDashboard = {
    summary: {
      totalInstances: 5,
      healthyInstances: 4,
      activeAlerts: 3,
      criticalAlerts: 1,
      avgLatency: 245,
    },
    instances: [
      {
        id: '17b0f286-a9e8-4a4d-a1db-54b74cb97cc3',
        name: 'Vultr Production Server',
        type: 'vultr-compute',
        status: 'healthy',
        region: 'ewr',
        endpoint: 'https://api.example.com',
        createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
        lastHealthCheck: new Date().toISOString(),
      },
      {
        id: 'instance-2',
        name: 'API Gateway',
        type: 'api',
        status: 'healthy',
        region: 'us-east-1',
        endpoint: 'https://gateway.example.com',
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
        lastHealthCheck: new Date().toISOString(),
      },
      {
        id: 'instance-3',
        name: 'Database Primary',
        type: 'database',
        status: 'healthy',
        region: 'us-east-1',
        endpoint: 'db.example.com:5432',
        createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
        lastHealthCheck: new Date().toISOString(),
      },
      {
        id: 'instance-4',
        name: 'Cache Server',
        type: 'cache',
        status: 'unhealthy',
        region: 'us-west-2',
        endpoint: 'cache.example.com:6379',
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
        lastHealthCheck: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
      },
      {
        id: 'instance-5',
        name: 'Worker Queue',
        type: 'queue',
        status: 'healthy',
        region: 'us-east-2',
        endpoint: 'queue.example.com',
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
        lastHealthCheck: new Date().toISOString(),
      },
    ],
    recentAlerts: [
      {
        id: 'alert-1',
        instanceId: 'instance-4',
        alertType: 'memory_usage_warning',
        severity: 'critical',
        message: 'Memory usage is critical: 95% (threshold: 90)',
        status: 'active',
        createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      },
      {
        id: 'alert-2',
        instanceId: '17b0f286-a9e8-4a4d-a1db-54b74cb97cc3',
        alertType: 'cpu_usage_warning',
        severity: 'high',
        message: 'CPU usage is high: 78% (threshold: 70)',
        status: 'active',
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'alert-3',
        instanceId: 'instance-2',
        alertType: 'response_time_warning',
        severity: 'medium',
        message: 'Response time is high: 1200ms (threshold: 1000)',
        status: 'active',
        createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'alert-4',
        instanceId: 'instance-3',
        alertType: 'disk_usage_warning',
        severity: 'low',
        message: 'Disk usage: 82% (threshold: 80)',
        status: 'resolved',
        createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        resolvedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
      },
    ],
    recentMetrics: [
      {
        id: 'metric-1',
        instanceId: '17b0f286-a9e8-4a4d-a1db-54b74cb97cc3',
        timestamp: Date.now(),
        metricName: 'cpu_usage',
        metricValue: 45.2,
        unit: 'percent',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'metric-2',
        instanceId: '17b0f286-a9e8-4a4d-a1db-54b74cb97cc3',
        timestamp: Date.now(),
        metricName: 'memory_usage_percent',
        metricValue: 62.8,
        unit: 'percent',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'metric-3',
        instanceId: 'instance-2',
        timestamp: Date.now(),
        metricName: 'response_time_ms',
        metricValue: 245,
        unit: 'milliseconds',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'metric-4',
        instanceId: 'instance-3',
        timestamp: Date.now(),
        metricName: 'disk_usage_percent',
        metricValue: 75.3,
        unit: 'percent',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'metric-5',
        instanceId: 'instance-4',
        timestamp: Date.now(),
        metricName: 'memory_usage_percent',
        metricValue: 95.1,
        unit: 'percent',
        createdAt: new Date().toISOString(),
      },
    ],
  };

  return NextResponse.json(mockDashboard, {
    headers: {
      'Cache-Control': 'no-store, max-age=0',
    },
  });
}
