#!/bin/bash

# Nephos Snowflake Setup Script
# This script provides guidance for setting up Snowflake

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}❄️  Nephos Snowflake Setup${NC}"
echo ""

echo -e "${YELLOW}This script will generate SQL commands to set up your Snowflake environment${NC}"
echo ""

# Get user input
read -p "Snowflake Account Identifier (e.g., xy12345.us-east-1): " ACCOUNT
read -p "Admin Username (default: ACCOUNTADMIN): " ADMIN_USER
ADMIN_USER=${ADMIN_USER:-ACCOUNTADMIN}
read -p "Nephos Database Name (default: NEPHOS): " DATABASE
DATABASE=${DATABASE:-NEPHOS}
read -p "Nephos Schema Name (default: PUBLIC): " SCHEMA
SCHEMA=${SCHEMA:-PUBLIC}
read -p "Nephos Warehouse Name (default: NEPHOS_WH): " WAREHOUSE
WAREHOUSE=${WAREHOUSE:-NEPHOS_WH}
read -p "Nephos Role Name (default: NEPHOS_ROLE): " ROLE
ROLE=${ROLE:-NEPHOS_ROLE}
read -p "Nephos User Name (default: NEPHOS_USER): " USER
USER=${USER:-NEPHOS_USER}

echo ""
echo -e "${GREEN}📝 Generated Snowflake Setup SQL${NC}"
echo ""
echo "Copy and execute the following SQL commands in your Snowflake console:"
echo ""
echo -e "${BLUE}--- Snowflake Setup for Nephos ---${NC}"
echo ""

cat << EOF
-- 1. Create Role
CREATE ROLE IF NOT EXISTS ${ROLE};
GRANT ROLE ${ROLE} TO ROLE SYSADMIN;

-- 2. Create Warehouse
CREATE WAREHOUSE IF NOT EXISTS ${WAREHOUSE}
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON WAREHOUSE ${WAREHOUSE} TO ROLE ${ROLE};
GRANT OPERATE ON WAREHOUSE ${WAREHOUSE} TO ROLE ${ROLE};

-- 3. Create Database and Schema
CREATE DATABASE IF NOT EXISTS ${DATABASE};
GRANT USAGE ON DATABASE ${DATABASE} TO ROLE ${ROLE};

USE DATABASE ${DATABASE};
CREATE SCHEMA IF NOT EXISTS ${SCHEMA};
GRANT USAGE ON SCHEMA ${DATABASE}.${SCHEMA} TO ROLE ${ROLE};
GRANT CREATE TABLE ON SCHEMA ${DATABASE}.${SCHEMA} TO ROLE ${ROLE};

-- 4. Create Tables
USE SCHEMA ${DATABASE}.${SCHEMA};

-- Metrics Table
CREATE TABLE IF NOT EXISTS METRICS (
    ID VARCHAR(255) PRIMARY KEY,
    INSTANCE_ID VARCHAR(255),
    TIMESTAMP TIMESTAMP_NTZ,
    METRIC_NAME VARCHAR(255),
    METRIC_VALUE FLOAT,
    UNIT VARCHAR(50),
    TAGS VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Alerts Table
CREATE TABLE IF NOT EXISTS ALERTS (
    ID VARCHAR(255) PRIMARY KEY,
    INSTANCE_ID VARCHAR(255),
    ALERT_TYPE VARCHAR(100),
    SEVERITY VARCHAR(50),
    MESSAGE TEXT,
    STATUS VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RESOLVED_AT TIMESTAMP_NTZ
);

-- Instances Table
CREATE TABLE IF NOT EXISTS INSTANCES (
    ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255),
    TYPE VARCHAR(100),
    STATUS VARCHAR(50),
    REGION VARCHAR(100),
    ENDPOINT VARCHAR(500),
    METADATA VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_HEALTH_CHECK TIMESTAMP_NTZ
);

-- Health Checks Table
CREATE TABLE IF NOT EXISTS HEALTH_CHECKS (
    ID VARCHAR(255) PRIMARY KEY,
    INSTANCE_ID VARCHAR(255),
    STATUS VARCHAR(50),
    LATENCY_MS FLOAT,
    ERROR_MESSAGE TEXT,
    TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Grant table permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ${DATABASE}.${SCHEMA} TO ROLE ${ROLE};
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ${DATABASE}.${SCHEMA} TO ROLE ${ROLE};

-- 5. Create User
CREATE USER IF NOT EXISTS ${USER}
  PASSWORD = 'CHANGE_ME_STRONG_PASSWORD'
  DEFAULT_ROLE = ${ROLE}
  DEFAULT_WAREHOUSE = ${WAREHOUSE}
  DEFAULT_NAMESPACE = ${DATABASE}.${SCHEMA};

GRANT ROLE ${ROLE} TO USER ${USER};

-- 6. Create Views for Analytics
CREATE OR REPLACE VIEW METRICS_HOURLY AS
SELECT
    INSTANCE_ID,
    METRIC_NAME,
    DATE_TRUNC('HOUR', TIMESTAMP) AS HOUR,
    AVG(METRIC_VALUE) AS AVG_VALUE,
    MAX(METRIC_VALUE) AS MAX_VALUE,
    MIN(METRIC_VALUE) AS MIN_VALUE,
    COUNT(*) AS SAMPLE_COUNT
FROM METRICS
GROUP BY INSTANCE_ID, METRIC_NAME, DATE_TRUNC('HOUR', TIMESTAMP);

CREATE OR REPLACE VIEW ACTIVE_ALERTS AS
SELECT *
FROM ALERTS
WHERE STATUS != 'RESOLVED'
ORDER BY CREATED_AT DESC;

CREATE OR REPLACE VIEW INSTANCE_HEALTH AS
SELECT
    i.ID,
    i.NAME,
    i.TYPE,
    i.STATUS,
    i.REGION,
    h.LATENCY_MS,
    h.TIMESTAMP AS LAST_CHECK,
    CASE
        WHEN h.STATUS = 'HEALTHY' THEN 'OK'
        WHEN h.STATUS = 'UNHEALTHY' THEN 'CRITICAL'
        ELSE 'UNKNOWN'
    END AS HEALTH_STATUS
FROM INSTANCES i
LEFT JOIN (
    SELECT INSTANCE_ID, STATUS, LATENCY_MS, TIMESTAMP,
           ROW_NUMBER() OVER (PARTITION BY INSTANCE_ID ORDER BY TIMESTAMP DESC) AS rn
    FROM HEALTH_CHECKS
) h ON i.ID = h.INSTANCE_ID AND h.rn = 1;

GRANT SELECT ON ALL VIEWS IN SCHEMA ${DATABASE}.${SCHEMA} TO ROLE ${ROLE};

-- Verification
SHOW GRANTS TO ROLE ${ROLE};
EOF

echo ""
echo -e "${GREEN}✅ SQL commands generated${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "1. Execute the SQL commands above in Snowflake"
echo "2. Change the password for user ${USER}"
echo "3. Update backend/.env with the following values:"
echo ""
echo "SNOWFLAKE_ACCOUNT=${ACCOUNT}"
echo "SNOWFLAKE_USERNAME=${USER}"
echo "SNOWFLAKE_PASSWORD=<your-password>"
echo "SNOWFLAKE_DATABASE=${DATABASE}"
echo "SNOWFLAKE_WAREHOUSE=${WAREHOUSE}"
echo "SNOWFLAKE_SCHEMA=${SCHEMA}"
echo ""
